/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: {
    pt?: string;
    en?: string;
  };
  slug?: {
    pt?: Slug;
    en?: Slug;
  };
  price?: {
    brl?: number;
    usd?: number;
  };
  category?: "desk-and-office" | "self-improvement" | "travel";
  description?: {
    pt?: Array<string>;
    en?: Array<string>;
  };
  features?: Array<{
    pt?: string;
    en?: string;
    _key: string;
  }>;
  colors?: Array<{
    colorName?: {
      pt?: string;
      en?: string;
    };
    colorHex?: string;
    images?: Array<{
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }>;
    _type: "colorOption";
    _key: string;
  }>;
  rating?: number;
  reviewsCount?: number;
  stock?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Product
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src\sanity\lib\queries.ts
// Variable: GET_PRODUCTS_QUERY
// Query: *[_type == "product"] | order(_createdAt desc) [$start...$end] {    _id,    name,    slug,    price,    category,    colors[] {      _key,      colorName,      colorHex,      images[] {        _key,        asset-> {          url,          metadata {            lqip,            dimensions          }        }      }    },    description {      pt[],      en[]    },    features[] {      _key,      pt,      en    },    rating,    reviewsCount,  }
export type GET_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: {
    pt?: string;
    en?: string;
  } | null;
  slug: {
    pt?: Slug;
    en?: Slug;
  } | null;
  price: {
    brl?: number;
    usd?: number;
  } | null;
  category: "desk-and-office" | "self-improvement" | "travel" | null;
  colors: Array<{
    _key: string;
    colorName: {
      pt?: string;
      en?: string;
    } | null;
    colorHex: string | null;
    images: Array<{
      _key: string;
      asset: {
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
    }> | null;
  }> | null;
  description: {
    pt: Array<string> | null;
    en: Array<string> | null;
  } | null;
  features: Array<{
    _key: string;
    pt: string | null;
    en: string | null;
  }> | null;
  rating: number | null;
  reviewsCount: number | null;
}>;

// Source: src\sanity\lib\queries.ts
// Variable: GET_PRODUCT_BY_SLUG_QUERY
// Query: *[_type == "product" && (slug.pt.current == $slug || slug.en.current == $slug)][0] {    _id,    name,    slug,    price,    category,    colors[] {      _key,      colorName,      colorHex,      images[] {        _key,        asset-> {          url,          metadata {            lqip, // O desfoque para o placeholder            dimensions // Útil para manter a proporção da imagem          }        }      }    },    description {      pt[],      en[]    },    features[] { _key, pt, en },    rating,    reviewsCount,    stock  }
export type GET_PRODUCT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: {
    pt?: string;
    en?: string;
  } | null;
  slug: {
    pt?: Slug;
    en?: Slug;
  } | null;
  price: {
    brl?: number;
    usd?: number;
  } | null;
  category: "desk-and-office" | "self-improvement" | "travel" | null;
  colors: Array<{
    _key: string;
    colorName: {
      pt?: string;
      en?: string;
    } | null;
    colorHex: string | null;
    images: Array<{
      _key: string;
      asset: {
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
    }> | null;
  }> | null;
  description: {
    pt: Array<string> | null;
    en: Array<string> | null;
  } | null;
  features: Array<{
    _key: string;
    pt: string | null;
    en: string | null;
  }> | null;
  rating: number | null;
  reviewsCount: number | null;
  stock: number | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "product"] | order(_createdAt desc) [$start...$end] {\n    _id,\n    name,\n    slug,\n    price,\n    category,\n    colors[] {\n      _key,\n      colorName,\n      colorHex,\n      images[] {\n        _key,\n        asset-> {\n          url,\n          metadata {\n            lqip,\n            dimensions\n          }\n        }\n      }\n    },\n    description {\n      pt[],\n      en[]\n    },\n    features[] {\n      _key,\n      pt,\n      en\n    },\n    rating,\n    reviewsCount,\n  }': GET_PRODUCTS_QUERY_RESULT;
    '\n  *[_type == "product" && (slug.pt.current == $slug || slug.en.current == $slug)][0] {\n    _id,\n    name,\n    slug,\n    price,\n    category,\n    colors[] {\n      _key,\n      colorName,\n      colorHex,\n      images[] {\n        _key,\n        asset-> {\n          url,\n          metadata {\n            lqip, // O desfoque para o placeholder\n            dimensions // \xDAtil para manter a propor\xE7\xE3o da imagem\n          }\n        }\n      }\n    },\n    description {\n      pt[],\n      en[]\n    },\n    features[] { _key, pt, en },\n    rating,\n    reviewsCount,\n    stock\n  }\n': GET_PRODUCT_BY_SLUG_QUERY_RESULT;
  }
}
